sonar.organization=felipeh3005
sonar.projectKey=felipeh3005_fullstack-javascript-project-139
sonar.projectName=fullstack-javascript-project-139

sonar.sources=frontend/src
sonar.tests=frontend/src

sonar.test.inclusions=frontend/src/**/*.test.js,frontend/src/**/*.test.jsx
sonar.exclusions=frontend/src/**/*.test.js,frontend/src/**/*.test.jsx,frontend/build/**,frontend/coverage/**,frontend/node_modules/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.coverage.exclusions=frontend/src/index.js,frontend/src/reportWebVitals.js,frontend/src/i18n.js
